iac:
  name: iac
  # define your GCP project name
  google:
    project:
    
  # define deployment "backend-java"
  backendjava:
    name: backend-java
    image:
      repository: backend-java
      tag: latest
    port: 8080
    replicas: 2
    strategy: RollingUpdate
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
        
  # define deployment "backend-php"
  backendphp:
    name: backend-php
    image:
      repository: backend-php
      tag: latest
    port: 9000
    replicas: 2
    strategy: RollingUpdate
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
        

  # define deployment "frontend-python"   
  frontendpython:
    name: frontend-python
    image:
      repository: frontend-python
      tag: latest
    port: 5000
    replicas: 1
    strategy: RollingUpdate
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
